name: Daily Trigger

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "30 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: trigger appveyor to build
        env:
          GH_REPO: ${{ github.repository }}
          TOKEN: ${{ secrets.APPVEYOR }}
          # GITHUB_ACTOR
          # IFS=', ' read -r -a array <<< "$string"
        run: |
          IFS='/' read -r -a array <<< "$GH_REPO" && \
          echo "${array[0]}" && \
          echo "${array[1]}" && \
          curl --request POST 'https://ci.appveyor.com/api/builds' \
          --header "Authorization: Bearer  ${TOKEN}" \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "accountName": '"${array[0]}" \
              ',"projectSlug": '"${array[1]}" \
              ',"branch": "main"
          }'
